// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:AzureFuncs.ExchangeRatesFunctions.Functions.IngressTriggerFunction.Ingest_DailyExchangeRates_QueueTrigger(System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:AzureFuncs.ExchangeRatesFunctions.Functions.EgressActivityFunction.GetExchangeRatesToEgressAsync(Microsoft.Azure.Functions.Worker.FunctionContext)~System.Threading.Tasks.Task{System.Collections.Generic.List{AzureFuncs.ExchangeRatesFunctions.Models.DailyExchangeRatesModel}}")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:AzureFuncs.ExchangeRatesFunctions.Functions.EgressActivityFunction.EgressExchangeRatesToAx7Async(System.Collections.Generic.List{AzureFuncs.ExchangeRatesFunctions.Models.DailyExchangeRatesModel},Microsoft.Azure.Functions.Worker.FunctionContext)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:AzureFuncs.ExchangeRatesFunctions.Functions.EgressActivityFunction.EgressExchangeRatesNotifyAsync(System.Boolean[],Microsoft.Azure.Functions.Worker.FunctionContext)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:AzureFuncs.ExchangeRatesFunctions.Functions.EgressOrchestrator.LogInformation(Microsoft.DurableTask.TaskOrchestrationContext,Microsoft.Extensions.Logging.ILogger,System.String,System.String)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:AzureFuncs.ExchangeRatesFunctions.Functions.EgressTriggers.EgressOrchestratorFunction_TimerStart(Microsoft.Azure.Functions.Worker.TimerInfo,Microsoft.DurableTask.Client.DurableTaskClient,Microsoft.Azure.Functions.Worker.FunctionContext)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:AzureFuncs.ExchangeRatesFunctions.Functions.IngressTriggerFunction.Ingest_DailyExchangeRates_BlobTrigger(System.String,System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:AzureFuncs.ExchangeRatesFunctions.Functions.IngressTriggerFunction.Ingest_DailyExchangeRates_ScheduleTrigger(AzureFuncs.ExchangeRatesFunctions.Models.TimerInfoModel)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:AzureFuncs.ExchangeRatesFunctions.Functions.EgressActivityFunction.EgressExchangeRatesToAx2009Async(System.Collections.Generic.List{AzureFuncs.ExchangeRatesFunctions.Models.DailyExchangeRatesModel},Microsoft.Azure.Functions.Worker.FunctionContext)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:AzureFuncs.ExchangeRatesFunctions.Functions.EgressActivityFunction.EgressExchangeRatesToDynamics365Async(System.Collections.Generic.List{AzureFuncs.ExchangeRatesFunctions.Models.DailyExchangeRatesModel},Microsoft.Azure.Functions.Worker.FunctionContext)~System.Threading.Tasks.Task{System.Boolean}")]
